### ISSUE TITLE
Bad link to the `cobra-cli` README.md

### ISSUE THREAD

**Issue by a-poor** [spf13/cobra.dev#6]
The following link in the "Getting Started" page is bad:

https://github.com/spf13/cobra.dev/blob/12b631a0cb2c7b9c98123e0feacc190f911dc33e/content/home/getting-started.md?plain=1#L39

I'm proposing changing this to the main README from the `cobra-cli`'s separate repo: https://github.com/spf13/cobra-cli/blob/main/README.md

I'm happy to create a PR to make the change. Thanks!

**Comment by a-poor** [comment]
Sorry, looks like this is already covered by #4 and fixed in #5

**Comment by SebTM** [comment]
There are three solutions now for the broken link, I was about to PR a fourth as I encounter the problem every-time I use the page - maybe we can resolve this by merging #5 which looks the most comprehensive solution.
